name: sharem_cli
description: A sample command-line application.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.2.0
  shelf: ^1.4.0
  args: ^2.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
