name: Dart CLI Build and Release

on:
  push:
      tags:
        - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    permissions: write-all
    name: Build CLI for Each OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Dependencies
        run: dart pub get

      - name: Build CLI
        run: |
          mkdir -p build/${{ matrix.os }}
          dart compile exe bin/main.dart -o build/${{ matrix.os }}/sharem

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-cli
          path: build/${{ matrix.os }}

  release:
    permissions: write-all
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-cli
          path: build/ubuntu

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-cli
          path: build/macos

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-cli
          path: build/windows

      - name: Zip Executables
        run: |
          cd build/ubuntu && zip sharem-linux-x86_64.zip sharem 
          cd ../../build/windows && zip sharem-windows-x86_64.zip sharem
          cd ../../build/macos && zip sharem-macos-x86_64.zip sharem
          cd ../../

      - name: List
        run: tree build

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 1.0.4
          name: Release
          makeLatest: "latest"
          artifacts: |
            build/windows/sharem-windows-x86_64.zip
            build/ubuntu/sharem-linux-x86_64.zip
            build/macos/sharem-macos-x86_64.zip

        

